name: Ubuntu-latest

on: [push, pull_request]

jobs:

  test:
  
    strategy:
      matrix:
        go-version: ['stable']
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run:  go get -t github.com/igulib/telegram_notifier

    - name: Test with coverage
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic  ./...
      env:
        BOT_TOKEN: ${{ secrets.TEST_TELEGRAM_BOT_TOKEN }}
        CHAT_IDS: ${{ secrets.TEST_TELEGRAM_CHAT_IDS }}

    - name: Process golang coverage data
      run: |
          set -x
          COVERAGE=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV
    - name: Create gist and coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.SECRET_FOR_GIST_CODECOV_BADGE }}
        gistID: 59a46b2a08ef7a2b28a5ba95f8a062b8
        filename: telegram_notifier-codecov-ubuntu.json
        label: codecov
        message: ${{ env.COVERAGE }}%
        color: ${{ env.COLOR }}
